# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mind Control
email:
description: >- # this means to ignore newlines until "baseurl:"
  A collection of learnings, projects, and ideas from a home automation enthusiast and dev.
  Content will be closer to stream-of-consciousness than a polished blog - enjoy!
github_username: akshaya-a
minimal_mistakes_skin: neon
search: true
url: "https://blog.akshaya.dev"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

logo: "/assets/images/logo.png"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives

jekyll-archives:
  enabled: 'all'
  layout: archive
  # layouts:
  #   year: year-archive
  #   tag: tag-archive
  permalinks:
    year: '/archive/year/:year/'
    tag: '/tags/:name/'

author:
  name   : "Akshaya Annavajhala (AK)"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Home automation enthusiast and dev @ Azure AI"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://blog.akshaya.dev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/akshaya-a"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/akshaya-a/"

teaser: /assets/images/blog-teaset-500x300.png

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/akshaya-a"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/akshaya-a/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
